### ISSUE TITLE
vue-router后端路由问题

### ISSUE THREAD

**Issue by JohnieXu** [sqaiyan/neteasemusic#1]
看到你写的路由router中有这样一段代码
```
{
path: '/simi/:id',
name: 'simi',
component: resolve => require(['@/pages/simi'], resolve)
}
```
这里component用函数的写法和先require相应的组件再`component: 组件名` ，这两者有什么区别吗？
新手，求解答！

**Comment by sqaiyan** [comment]
这个是按需加载组件的写法，可以看router的文档。这个是避免一次性打包所有组件造成首页打包文件过大的问题。这个是用到这个组件时候才加载对应的打包的js。利弊自己平衡

**Comment by JohnieXu** [comment]
好的，多谢啦。
