### ISSUE TITLE
Vue版不知道为什么总是打不开网页

### ISSUE THREAD

**Issue by meidawei** [sqaiyan/neteasemusic#5]
Vue版打不开网页，我修改了端口还是不行

axios.defaults.baseURL = 'http://localhost:3000/v1/';
这里我修改了3000作为端口还是会报错
不知道是什么原因的
__

**Comment by wolong438** [comment]
Access to XMLHttpRequest at 'http://localhost:3000/v1/personalized/djprogram' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

app.all('*', function(req, res, next) {
	res.header("Access-Control-Allow-Origin", "*");
	res.header("Access-Control-Allow-Headers", "X-Requested-With");
	res.header("Access-Control-Allow-Methods", "PUT,POST,GET,DELETE,OPTIONS");
	res.header("X-Powered-By", ' 3.2.1')
	res.header("Content-Type", "application/json;charset=utf-8");
	next();
});
前后端都通了，看见后端有处理跨域问题，但前端加载后端数据还是提示存在跨域
